### ISSUE TITLE
Proxy emoticons

### ISSUE THREAD

**Issue by lexek** [lexek/chat#187]
* [ ]  #173 - [sc2tv] Use native emoticons 
* [ ]  #35 - [GoodGame] Use native emoticons
* [ ]  #34 - [Twitch] Use native emoticons
