### ISSUE TITLE
Улучшения UI

### ISSUE THREAD

**Issue by lexek** [lexek/chat#59]
- [ ] #45 - Использовать нативный скролл для мобильных устройств
- [x] ~~#61 - Улучшить интерфейс тикетов для пользователей~~
- [x] ~~#60 - решить проблемы с показом ошибок в процессе создания или прикрепления аккаунта при входе через социальные сети~~
- [x] ~~#69 - Переработать интерфейс профиля~~
